Update patch set 1
Patch Set 1:

Error: No Package found for python2-nose-exclude
    u-c is 0.5.0, fedora has 0.4.1 which has python2- version
Error: No Package found for python2-openstack-nose-plugin
    fedora 0.11-14 can be rebuild to get python2- version
Error: No Package found for python2-selenium
     u-c is 3.8.1, fedora latest build is 3.7.0

Patch-set: 1
Reviewer: Gerrit User 403 <403@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0